(define (double x) (+ x x))
(define (halve x) (/ x 2))
(define (mstep a b r)
  (cond ((or (= a 0) (= b 0)) 0)
        ((= b 1) (+ a r))
	((= (remainder b 2) 0) (mstep (double a) (halve b) r))
        (else (mstep a (- b 1) (+ r a)))
   )
  )
(define (m a b)
  (mstep a b 0)
  )
